"""Mutation battery for the library's tests. Each mutant breaks one line of a scratch copy of the
library, and every tests/test_*.lua must then fail. Run from anywhere:

    python tests/mutate.py

An anchor that matches anything other than exactly once is reported and counts as a failure: fix
the anchor, never drop the mutant.
"""
import glob
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA = os.environ.get('LUA51', r'C:\Users\Big Daddy\Documents\Tools\lua-5.1.5\lua5.1.exe')
GATE = 'if lib.host ~= addonName then return end'

MUTANTS = [
    # Which copy wins
    ('Tokens.lua', GATE, '', 'Tokens host check removed'),
    ('Context.lua', GATE, '', 'Context host check removed'),
    ('Kit.lua', GATE, '', 'Kit host check removed'),
    ('Controls.lua', GATE, '', 'Controls host check removed'),
    ('Window.lua', GATE, '', 'Window host check removed'),
    ('Context.lua', GATE, 'if not lib.host then return end', 'Context check only asks for a host'),
    ('Context.lua', 'lib.Context = lib.Context or {}', 'lib.Context = {}', 'methods table rebuilt per copy'),
    ('Context.lua', 'lib.contextMeta = lib.contextMeta or { __index = lib.Context }', 'lib.contextMeta = { __index = lib.Context }', 'metatable rebuilt per copy'),
    ('Context.lua', 'return setmetatable({ opts = kept }, lib.contextMeta)', 'return setmetatable({ opts = kept }, { __index = Context })', 'context gets a private metatable'),
    ('EverythingUI.lua', 'if not lib then return end', 'lib = lib or LibStub(MAJOR)', 'early return removed'),
    ('EverythingUI.lua', 'lib.host = addonName', 'lib.host = lib.host or addonName', 'host kept from the first copy'),
    ('EverythingUI.lua', r'"\\Libs\\EverythingUI\\Media\\"', r'"\\Libs\\EverythingUI\\Media"', 'media path trailing separator'),
    ('EverythingUI.xml', '    <Script file="Tokens.lua"/>\n    <Script file="Context.lua"/>', '    <Script file="Context.lua"/>\n    <Script file="Tokens.lua"/>', 'XML order'),

    # Tokens
    ('Tokens.lua', 'zhTW = true ', '', 'zhTW dropped from the client-font locales'),
    ('Tokens.lua', r'STANDARD_TEXT_FONT or "Fonts\\FRIZQT__.TTF"', 'STANDARD_TEXT_FONT', 'no client font fallback'),
    ('Tokens.lua', 'hex("3A3F48")', 'hex("3A3F49")', 'borderStrong off by one'),
    ('Tokens.lua', 'accentSoft = 0.18', 'accentSoft = 0.2', 'accentSoft alpha'),
    ('Tokens.lua', 'CDM     = { accent = hex("D9A520"), accentText = hex("16181C") }', 'CDM     = { accent = hex("D9A520"), accentText = { 1, 1, 1 } }', 'Cooldown Master accent text'),
    ('Tokens.lua', 'labelColumn        = 150', 'labelColumn        = 160', 'label column'),
    ('Tokens.lua', 'nav        = { size = 13, weight = "Medium",', 'nav        = { size = 13, weight = "Regular",', 'nav weight'),

    # The context
    ('Context.lua', '        if not OPTS[key] then\n', '        if false then\n', 'unknown opts accepted'),
    ('Context.lua', '            if spec.required then', '            if false then', 'required opts not required'),
    ('Context.lua', 'if type(c) ~= "number" or c < 0 or c > 1 then return false end', 'if type(c) ~= "number" then return false end', 'rgb range unchecked'),
    ('Context.lua', '    if (opts.getLastTab == nil) ~= (opts.setLastTab == nil) then', '    if false then', 'tab getter pair unchecked'),
    ('Context.lua', '    if (opts.getWindowScale == nil) ~= (opts.setWindowScale == nil) then', '    if false then', 'scale pair unchecked'),
    ('Context.lua', '    kept.accent = copyRGB(opts.accent)\n', '', 'accent not copied'),
    ('Context.lua', 'or { 1, 1, 1 }', 'or { 0, 0, 0 }', 'accentText default'),
    ('Context.lua', 'a[1] + (1 - a[1]) * mix', 'a[1] + (1 - a[1]) * 0.3', 'accentHi mix'),
    ('Context.lua', 'error("EverythingUI: NewContext expects an opts table", 2)', 'error("EverythingUI: NewContext expects an opts table", 1)', 'error level'),
    ('Context.lua', '    return tokens.fonts[t.weight], t.size, tokens.fontFlags', '    return tokens.fonts.Regular, t.size, tokens.fontFlags', 'Font ignores weight'),
    ('Context.lua', '    if opts.discord and not labels.discord then', '    if false then', 'discord without a label accepted'),
    ('Context.lua', '        if not LABELS[key] then', '        if false then', 'unknown label accepted'),
    ('Context.lua', '    kept.labels = labels\n', '', 'labels not copied'),

    # Kit
    ('Kit.lua', '        if InCombatLockdown() then return end\n        f:EnableKeyboard(true)', '        f:EnableKeyboard(true)', 'OnShow takes the keyboard in combat'),
    ('Kit.lua', '    frame:SetScript("OnKeyDown", function(f, key)\n        if InCombatLockdown() then return end\n', '    frame:SetScript("OnKeyDown", function(f, key)\n', 'OnKeyDown runs in combat'),
    ('Kit.lua', '            f:SetPropagateKeyboardInput(false)\n            f:Hide()', '            f:SetPropagateKeyboardInput(true)\n            f:Hide()', 'Escape propagates'),
    ('Kit.lua', '            f:SetPropagateKeyboardInput(false)\n            f:Hide()', '            f:SetPropagateKeyboardInput(false)', 'Escape never hides'),
    ('Kit.lua', '        else\n            f:SetPropagateKeyboardInput(true)\n        end', '        end', 'other keys swallowed'),
    ('Kit.lua', '    frame:HookScript("OnHide", function(f) f:EnableKeyboard(false) end)\n', '', 'keyboard kept after hide'),
    ('Kit.lua', '        if h and h > 0 then return 768 / h / scale end', '        if h and h > 0 then return 720 / h / scale end', 'pixel fallback constant'),
    ('Kit.lua', '    if not fs:GetFont() then fs:SetFontObject(GameFontHighlight) end\n', '', 'no font fallback'),
    ('Kit.lua', '    if not fs:GetFont() then fs:SetFontObject(GameFontHighlight) end\n    fs:SetShadowOffset(0, 0)\n', '    if not fs:GetFont() then fs:SetFontObject(GameFontHighlight) end\n', 'shadow offset left'),
    ('Kit.lua', '    fs:SetFontObject(GameFontHighlight)\n    fs:SetShadowOffset(0, 0)\n', '    fs:SetFontObject(GameFontHighlight)\n', 'data text keeps the shadow offset'),
    ('Kit.lua', '        bar:SetShown(yrange > 0)', '        bar:Show()', 'scroll bar always shown'),
    ('Kit.lua', '        if bar:GetValue() > yrange then bar:SetValue(yrange) end\n', '', 'shrinking range keeps the position'),
    ('Kit.lua', '            thumb:SetHeight(math.max(MIN_THUMB, length * view / (view + yrange)))', '            thumb:SetHeight(length * view / (view + yrange))', 'thumb has no floor'),
    ('Kit.lua', '            thumb:SetHeight(math.max(MIN_THUMB, length * view / (view + yrange)))', '            thumb:SetHeight(math.max(MIN_THUMB, view * view / (view + yrange)))', 'thumb sized from the view, not its track'),
    ('Kit.lua', '        if view > 0 and length > 0 then', '        if view > 0 then', 'thumb sized before the bar has a length'),
    ('Kit.lua', '        bar:SetValue(math.min(max, math.max(0, bar:GetValue() - delta * WHEEL_STEP)))', '        bar:SetValue(bar:GetValue() + delta * WHEEL_STEP)', 'wheel direction'),
    ('Kit.lua', 'local WHEEL_STEP = 48', 'local WHEEL_STEP = 40', 'wheel step'),
    ('Kit.lua', '    bar:SetScript("OnValueChanged", function(_, v) sf:SetVerticalScroll(v) end)\n', '', 'bar never scrolls'),

    # The window
    ('Window.lua', '    f:SetClampedToScreen(true)\n', '', 'not clamped'),
    ('Window.lua', '    f:SetFrameStrata("DIALOG")', '    f:SetFrameStrata("HIGH")', 'wrong strata'),
    ('Window.lua', '                t._built = true\n', '', 'built on every view'),
    ('Window.lua', '            if t.refresh then t.refresh(self, t._content) end\n', '', 'refresh never runs'),
    ('Window.lua', '                if c.Refresh then c:Refresh() end\n', '', 'controls never refresh'),
    ('Window.lua', '    if set then set(id) end\n    self._current = id', '    self._current = id', 'last tab never saved'),
    ('Window.lua', '    self:SelectTab(found and want or (tabs[1] and tabs[1].id))', '    self:SelectTab(want)', 'no fallback for an unknown tab'),
    ('Window.lua', '        if capped < s and set then set(capped) end\n', '', 'clamp not written back'),
    ('Window.lua', '        local capped = math.min(s, uw / sp.windowWidth, uh / sp.windowHeight)', '        local capped = math.min(s, uw / sp.windowWidth)', 'height not clamped'),
    ('Window.lua', '        f:SetPoint("CENTER", UIParent, "BOTTOMLEFT", cx * oldEff / newEff, cy * oldEff / newEff)', '        f:SetPoint("CENTER", UIParent, "BOTTOMLEFT", cx, cy)', 'center not rescaled'),
    ('Window.lua', '    kit.SnapAll(self)\n', '', 'lines never re-snap'),
    ('Window.lua', '                t._footerBuilt = true\n', '', 'footer built on every view'),
    ('Window.lua', '            if t._footer then t._footer:Show() end\n', '', 'footer never shown'),
    ('Window.lua', '            if t._footer then t._footer:Hide() end\n', '', 'footer never hidden'),
    ('Window.lua', '            f.section:SetText(t.title)\n', '', 'header never names the section'),
    ('Window.lua', '        if tip then tip:Hide() end\n', '', 'tooltip left up on hide'),
    ('Window.lua', '    b.active:SetShown(active)', '    b.active:Show()', 'every nav item looks selected'),
    ('Window.lua', '    if b.icon then b.icon:SetVertexColor(ctx:Color(active and "accentHi" or "navText")) end', '    if b.icon then b.icon:SetVertexColor(ctx:Color("navText")) end', 'icon never takes the accent'),
    ('Window.lua', '    table.sort(tabs, function(a, b) return (a.order or 100) < (b.order or 100) end)', '', 'tabs unsorted'),
    ('Window.lua', '        if TAB_FIELDS[key] ~= type(v) then', '        if false then', 'tab fields unchecked'),
    ('Window.lua', '        local d = ctx:CreateButton(sidebar, labels.discord, width, function() opts.discord() end)', '        local d = ctx:CreateButton(sidebar, labels.discord, width, function() end)', 'Discord click does nothing'),
    ('Window.lua', '    close:SetScript("OnClick", function() f:Hide() end)\n', '', 'close does nothing'),
    ('Window.lua', '            t._holder:Show()\n', '', 'tab never shown'),
    ('Window.lua', '            t._holder:Hide()\n', '', 'other tabs never hidden'),
    ('Window.lua', '    local width = sp.windowWidth - sp.sidebarWidth - sp.contentSides * 2', '    local width = sp.windowWidth - sp.sidebarWidth', 'content width ignores padding'),
    ('Window.lua', '            settle(self, t)\n', '', 'never settled on view'),
    ('Window.lua', '    ctx:MeasureContent(t._content)\n', '', 'never measured'),

    # Controls
    ('Controls.lua', '        t:HookScript("OnEnter", function()', '        t:SetScript("OnEnter", function()', 'tooltip set rather than hooked'),
    ('Kit.lua', '    if title then tip:SetText(title, TOOLTIP_TITLE[1], TOOLTIP_TITLE[2], TOOLTIP_TITLE[3], 1, true) end', '    if title then tip:SetText(title, 1, 1, 1, 1, true) end', 'tooltip title not gold'),
    ('Controls.lua', '            if not w or w <= 0 then w = 90 end', '            if not w then w = 90 end', 'zero width accepted'),
    ('Controls.lua', '        kit.Edge(self, b, "navText")', '        kit.Edge(self, b, "divider")', 'secondary outline color'),
    ('Controls.lua', '    if not BUTTON_STYLES[style] then', '    if false then', 'unknown style accepted'),
    ('Controls.lua', '            if not (o and o.IsShown and o:IsShown() and o.GetBottom) then return end', '            if not (o and o.GetBottom) then return end', 'hidden children measured'),
    ('Controls.lua', '        for _, region in ipairs({ content:GetRegions()  }) do consider(region) end\n', '', 'regions not measured'),
    ('Controls.lua', 'local BOTTOM_PADDING = 24', 'local BOTTOM_PADDING = 28', 'bottom padding'),
    ('Controls.lua', '            b:SetWidth(w + BUTTON_PADDING * 2)', '            b:SetWidth(w + BUTTON_PADDING)', 'button padding'),

    # Phase 1 step 2: the shared kit pieces
    ('Dropdown.lua', GATE, '', 'Dropdown host check removed'),
    ('Card.lua', GATE, '', 'Card host check removed'),
    ('Context.lua', '    testSound       = true,\n', '', 'testSound label refused'),
    ('Tokens.lua', 'popupRowHeight     = 22', 'popupRowHeight     = 24', 'popup row height'),
    ('Kit.lua', 'TOOLTIP_TITLE[3], 1, true)', 'TOOLTIP_TITLE[3], true)', 'tooltip alpha dropped'),
    ('Kit.lua', '    return made\nend', '    return {}\nend', 'Edge returns no lines'),
    ('Kit.lua', '    fs:SetFontObject(GameFontHighlight)\n    fs:SetShadowOffset(0, 0)\n    fs:SetJustifyH("LEFT")', '    fs:SetFont(STANDARD_TEXT_FONT, 12, "")\n    fs:SetShadowOffset(0, 0)\n    fs:SetJustifyH("LEFT")', 'data text given a font file'),

    # Controls
    ('Controls.lua', '    if v == nil then\n        error(("EverythingUI: no spacing named', '    if false then\n        error(("EverythingUI: no spacing named', 'unknown spacing accepted'),
    ('Controls.lua', '        if w > 0 then frame:SetHitRectInsets(0, -(w + lib.tokens.spacing.checkboxGap), 0, 0) end', '        if w > 0 then frame:SetHitRectInsets(0, -(w + 8), 0, 0) end', 'tooltip widens the checkbox by the old gap'),
    ('Controls.lua', '        paint()\n        setter(btn:GetChecked() and true or false)', '        setter(btn:GetChecked() and true or false)', 'checkbox not repainted on click'),
    ('Controls.lua', '        setChecked(btn, v)\n        paint()\n', '        setChecked(btn, v)\n', 'checkbox put back by hand not repainted'),
    ('Controls.lua', 'line:SetColorTexture(ctx:Color(on and "accent" or "borderStrong"))', 'line:SetColorTexture(ctx:Color("borderStrong"))', 'checked edge stays borderStrong'),
    ('Controls.lua', '        fill:SetColorTexture(ctx:Color(on and "accent" or "input"))', '        fill:SetColorTexture(ctx:Color("input"))', 'checked fill stays input'),
    ('Controls.lua', '        mark:SetShown(on)\n', '        mark:Show()\n', 'check mark always shown'),
    ('Controls.lua', '    cb.label:SetPoint("LEFT", cb, "RIGHT", sp.checkboxGap, 0)', '    cb.label:SetPoint("LEFT", cb, "RIGHT", 4, 0)', 'checkbox label gap'),
    ('Controls.lua', '    if labelW > 0 then cb:SetHitRectInsets(0, -(labelW + sp.checkboxGap), 0, 0) end\n', '', 'checkbox label not clickable'),
    ('Controls.lua', '    cb.Refresh = function(btn) btn:SetChecked(getter() and true or false) end', '    cb.Refresh = function() end', 'checkbox Refresh ignores the getter'),
    ('Controls.lua', '    content._controls[#content._controls + 1] = cb\n', '', 'checkbox not registered'),
    ('Controls.lua', '        if not suppress then setter(stepped) end', '        setter(stepped)', 'slider Refresh writes back'),
    ('Controls.lua', '        suppress = true\n        slider:SetValue(getter() or minV)\n        suppress = false', '        slider:SetValue(getter() or minV)', 'slider suppress never raised'),
    ('Controls.lua', '        local stepped = step and (math.floor((v - minV) / step + 0.5) * step + minV) or v', '        local stepped = v', 'slider value not stepped'),
    ('Controls.lua', '        if minV < 0 and (tonumber(s) or 0) > 0 then s = "+" .. s end', '        if minV < 0 and v > 0 then s = "+" .. s end', 'plus sign read off the raw value'),
    ('Controls.lua', '        if minV < 0 and (tonumber(s) or 0) > 0 then s = "+" .. s end', '        if (tonumber(s) or 0) > 0 then s = "+" .. s end', 'plus sign on every range'),
    ('Controls.lua', '        if minV < 0 and (tonumber(s) or 0) > 0 then s = "+" .. s end\n', '', 'plus sign dropped'),
    ('Controls.lua', '    return "%." .. math.max(1, math.ceil(-math.log10(s))) .. "f"', '    return "%.1f"', 'decimals ignore the step'),
    ('Controls.lua', '        slider:SetPoint("LEFT", holder, "LEFT", columnEdge(label, w), 0)', '        slider:SetPoint("LEFT", holder, "LEFT", 0, 0)', 'slider ignores the label column'),
    ('Controls.lua', '    return w + lib.tokens.spacing.controlGap', '    return w', 'label column has no gap'),
    ('Controls.lua', '    slider:SetPoint("RIGHT", holder, "RIGHT", -(sp.valueColumn + sp.controlGap), 0)', '    slider:SetPoint("RIGHT", holder, "RIGHT", -sp.valueColumn, 0)', 'slider runs into the value column'),
    ('Controls.lua', '    fill:SetPoint("RIGHT", thumb, "CENTER")', '    fill:SetPoint("RIGHT", track, "RIGHT")', 'slider fill not tied to the thumb'),
    ('Controls.lua', '    thumb:SetSize(sp.thumbWidth, sp.thumbHeight)', '    thumb:SetSize(sp.thumbHeight, sp.thumbHeight)', 'slider thumb size'),
    ('Controls.lua', '    thumb:SetDrawLayer("OVERLAY")\n', '', 'slider fill drawn over the thumb'),
    ('Controls.lua', '    if slider.SetObeyStepOnDrag then slider:SetObeyStepOnDrag(true) end\n', '', 'slider ignores its step on drag'),
    ('Controls.lua', '    if not label then return 0 end\n', '', 'unlabelled slider claims a column'),
    ('Dropdown.lua', '        local left = label and (w + sp.controlGap) or 0', '        local left = w + sp.controlGap', 'unlabelled field claims a column'),
    ('Controls.lua', '    if #options > MAX_SEGMENTS then\n        return self:CreateDropdown', '    if false then\n        return self:CreateDropdown', 'four choices drawn segmented'),
    ('Controls.lua', 'local MAX_SEGMENTS = 3', 'local MAX_SEGMENTS = 4', 'segment limit'),
    ('Controls.lua', '    if natural > avail then', '    if false then', 'segmented width never checked'),
    ('Controls.lua', '    local avail = (content.GetWidth and content:GetWidth() or 0) - sp.rowPadding * 2\n        - columnEdge(label, sp.labelColumn)', '    local avail = (content.GetWidth and content:GetWidth() or 0) - sp.rowPadding * 2', 'fit test forgets the label column'),
    ('Controls.lua', '        holder:Hide()\n        return self:CreateDropdown', '        return self:CreateDropdown', 'failed segmented attempt left shown'),
    ('Controls.lua', '            local on = (b.value == active)', '            local on = true', 'every segment painted selected'),
    ('Controls.lua', '            if setter then setter(b.value) end', '            if setter then setter(b.txt:GetText()) end', 'segment hands the setter its label'),
    ('Controls.lua', '            if setter then setter(b.value) end\n            paint(b.value)', '            if setter then setter(b.value) end', 'segment click not repainted'),
    ('Controls.lua', '        x = x + w + ((i < #options) and sp.segmentGap or 0)', '        x = x + w', 'no gap between segments'),
    ('Controls.lua', '            self:AttachTooltip(btn, opt.label, opt.tip)', '            self:AttachTooltip(btn, tipTitle, tipBody)', 'per-option tip ignored'),
    ('Controls.lua', '    holder.Refresh = function() paint(getter and getter()) end\n    content._controls[#content._controls + 1] = holder\n', '    holder.Refresh = function() paint(getter and getter()) end\n', 'radio group not registered'),
    ('Controls.lua', '    if control then control:SetAlpha(on and 1 or DIM_ALPHA) end', '    if control then control:SetAlpha(on and 1 or DIM_ALPHA) control:EnableMouse(on) end', 'dimming takes the mouse'),
    ('Controls.lua', 'local DIM_ALPHA = 0.4', 'local DIM_ALPHA = 0.5', 'dim alpha'),
    ('Controls.lua', '            local r = (cb:GetWidth() or 0) + gap + w', '            local r = (cb:GetWidth() or 0) + w', 'satellite reach forgets the label gap'),
    ('Controls.lua', '            if r > reach then reach = r end', '            reach = r', 'satellite column follows the last label'),
    ('Controls.lua', '    if reach <= 0 then reach = SATELLITE_FLOOR end\n', '', 'satellite floor dropped'),
    ('Controls.lua', '        local w = p.label:GetStringWidth() or 0\n        if w > widest then widest = w end', '        local w = p.label:GetStringWidth() or 0\n        widest = w', 'picker column follows the last label'),
    ('Controls.lua', '        if need > p:GetWidth() then p:SetWidth(need) end\n', '', 'picker holder never grows'),
    ('Controls.lua', '        c:SetLabelWidth(c._euiDependent and (widest - extra) or widest)', '        c:SetLabelWidth(widest)', 'dependent column not shortened'),
    ('Controls.lua', '        if c._euiDependent then w = w + extra end\n', '', 'dependent label measured without its indent'),
    ('Controls.lua', '    local widest = sp.labelColumn\n', '    local widest = 0\n', 'label column can shrink below the token'),
    ('Controls.lua', '        if c.SetLabelWidth then controls[#controls + 1] = c end', '        controls[#controls + 1] = c', 'a control with no column is handed one'),

    # The dropdown and its shared list
    ('Dropdown.lua', '            xpcall(function() onPick(opt.value) end, geterrorhandler())\n            p:Hide()\n', '            p:Hide()\n            xpcall(function() onPick(opt.value) end, geterrorhandler())\n', 'pick runs after the list hides'),
    ('Dropdown.lua', '            xpcall(function() onPick(opt.value) end, geterrorhandler())', '            onPick(opt.value)', 'a raising pick escapes'),
    ('Dropdown.lua', '    if shared.popup then return shared.popup end\n', '', 'a new list per open'),
    ('Dropdown.lua', '    shared.popup = p\n', '', 'list not shared'),
    ('Dropdown.lua', '    p:SetScale((base and base > 0) and (anchor:GetEffectiveScale() / base) or 1)', '    p:SetScale(1)', 'list ignores the window scale'),
    ('Dropdown.lua', "    if ((anchor:GetBottom() or 0) * anchor:GetEffectiveScale()) - (h * p:GetEffectiveScale()) < 0 then", '    if false then', 'list always opens below'),
    ('Dropdown.lua', '    else\n        kit.Style(ctx, themed, "label")\n    end\n', '    end\n', 'row font not put back'),
    ('Dropdown.lua', '        if not themed:GetFont() then kit.Style(ctx, themed, "label") end\n', '', 'a broken preview face left fontless'),
    ('Dropdown.lua', '    local useData = not (path and path ~= "") and kit.NeedsClientFont(s)', '    local useData = false', 'client font never used'),
    ('Dropdown.lua', '    local useData = not (path and path ~= "") and kit.NeedsClientFont(s)', '    local useData = true', 'client font used for every string'),
    ('Dropdown.lua', '    themed:SetTextColor(ctx:Color(color))\n', '', 'row color not set'),
    ('Dropdown.lua', 'isActive and "accentHi" or "text")', '"text")', 'current choice not marked'),
    ('Dropdown.lua', '        if b.swatch then\n            b.swatchBg:Hide()\n            b.swatch:Hide()\n        end\n', '', 'swatch kept by a plain list'),
    ('Dropdown.lua', '        placeText(b, PAD)\n', '', 'text left past an old swatch'),
    ('Dropdown.lua', '            b:SetScript("OnEnter", nil)\n            b:SetScript("OnLeave", nil)\n', '', 'row tip carried into the next list'),
    ('Dropdown.lua', '    for i = #opts + 1, #p.rows do p.rows[i]:Hide() end\n', '', 'unused rows left shown'),
    ('Dropdown.lua', '    p.bar:SetValue(want)\n', '', 'list never scrolls to its choice'),
    ('Dropdown.lua', '    p.bar:SetShown(scrolls)\n', '', 'long list has no bar'),
    ('Dropdown.lua', '    p.scroll:SetPoint("BOTTOMRIGHT", p, "BOTTOMRIGHT", scrolls and -BAR_ROOM or -1, POPUP_INSET)', '    p.scroll:SetPoint("BOTTOMRIGHT", p, "BOTTOMRIGHT", -1, POPUP_INSET)', 'rows run under the bar'),
    ('Dropdown.lua', '(scrolls and (BAR_ROOM + 1) or 2)', '2', 'row width ignores the bar'),
    ('Dropdown.lua', '    local shown = math.min(#opts, maxRows)', '    local shown = #opts', 'list grows past ten rows'),
    ('Dropdown.lua', '    p:HookScript("OnShow", function() closer:Show() end)\n', '', 'outside click not caught'),
    ('Dropdown.lua', '    kit.CloseOnEscape(p)\n', '', 'Escape does not close the list'),
    ('Dropdown.lua', '    p.owner = ctx._window\n', '', 'list owner not recorded'),
    ('Dropdown.lua', '        if getTip then getTip():Hide() end\n', '', 'closing the list leaves a tip up'),
    ('Dropdown.lua', '                shown = opt.label\n', '                shown = tostring(opt.value)\n', 'field shows the value, not the label'),
    ('Dropdown.lua', '        if speaker then speaker:SetShown(current ~= nil and current ~= NO_SOUND) end', '        if speaker then speaker:Show() end', 'speaker shown for no sound'),
    ('Dropdown.lua', '        speaker:SetScript("OnClick", function() onTest(getter()) end)', '        speaker:SetScript("OnClick", function() end)', 'speaker plays nothing'),
    ('Dropdown.lua', '        self:AttachTooltip(speaker, label, self.opts.labels.testSound)', '        self:AttachTooltip(speaker, label)', 'speaker tip loses the host label'),
    ('Dropdown.lua', '        if speaker then left = left + SPEAKER + SPEAKER_GAP end\n', '', 'field sits under the speaker'),
    ('Dropdown.lua', '        local left = label and (w + sp.controlGap) or 0', '        local left = 0', 'field ignores the label column'),
    ('Dropdown.lua', '    holder.Refresh = refresh\n    if tooltip then self:AttachTooltip(holder, label, tooltip) end\n    content._controls[#content._controls + 1] = holder\n', '    holder.Refresh = refresh\n    if tooltip then self:AttachTooltip(holder, label, tooltip) end\n', 'dropdown not registered'),
    ('Dropdown.lua', '            setter(v)\n            refresh()', '            setter(v)', 'field not refreshed after a pick'),
    ('Dropdown.lua', '        if decorate then decorate(btn, current) end\n', '', 'field never decorated'),
    ('Dropdown.lua', '    local chevron = kit.Icon(self, btn, "chevron-down", sp.chevron, "muted")', '    local chevron = kit.Icon(self, btn, "chevron-down", sp.chevron, "text")', 'chevron color'),
    ('Window.lua', '        if list and list.owner == f then list:Hide() end\n', '', 'window leaves its list open'),
    ('Window.lua', '        if list and list.owner == f then list:Hide() end', '        if list then list:Hide() end', 'window closes another addon\'s list'),

    # Cards
    ('Card.lua', '    card:SetFrameLevel(level)\n', '', 'card above its controls'),
    ('Card.lua', '    panel:SetFrameLevel(level)\n', '', 'panel above its controls'),
    ('Card.lua', '    row:SetFrameLevel(card:GetFrameLevel())\n', '', 'row above its controls'),
    ('Card.lua', '        top = h + sp.groupLabelGap', '        top = h', 'no gap under the group label'),
    ('Card.lua', '        if not h or h <= 0 then h = lib.tokens.typography.groupLabel.size end\n', '', 'unmeasured label overlaps the panel'),
    ('Card.lua', '            y = y + row:GetHeight()\n', '', 'rows not stacked'),
    ('Card.lua', '        if shown then\n            if row.fitHeight and', '        do\n            if row.fitHeight and', 'hidden rows keep their place'),
    ('Card.lua', '        if row.control:IsShown() then h = h + row:GetHeight() end', '        h = h + row:GetHeight()', 'hidden rows counted in the height'),
    ('Card.lua', '        if row.control:IsShown() then h = h + row:GetHeight() end', '        if row:IsShown() then h = h + row:GetHeight() end', 'height reads the row, not its control'),
    ('Card.lua', '        local shown = row.control:IsShown() and true or false', '        local shown = row:IsShown() and true or false', 'layout reads the row, not its control'),
    ('Card.lua', '        row:SetShown(shown)\n', '', 'row stays up with its control hidden'),
    ('Controls.lua', '    local fs = kit.Text(self, content, style or "label")', '    local fs = kit.Text(self, content, "label")', 'CreateText ignores its style'),
    ('Controls.lua', '    b:GetDisabledTexture():SetVertexColor(self:Color("borderStrong"))', '    b:GetDisabledTexture():SetVertexColor(self:Color("navText"))', 'a disabled icon looks enabled'),
    ('Controls.lua', '        if flip then t:SetTexCoord(0, 1, 1, 0) end\n', '', 'icon never flips'),
    ('Controls.lua', '        t:SetSize(ICON_SIZE, ICON_SIZE)\n', '', 'icon stretched over the whole button'),
    ('Card.lua', '            row.divider:SetShown(not first)', '            row.divider:Show()', 'divider above the first row'),
    ('Card.lua', '    control:SetPoint("LEFT", row, "LEFT", dependent and sp.dependentIndent or sp.rowPadding, 0)', '    control:SetPoint("LEFT", row, "LEFT", sp.rowPadding, 0)', 'dependent not indented'),
    ('Card.lua', 'dependent and sp.dependentRowHeight or sp.rowHeight', 'sp.rowHeight', 'dependent row full height'),
    ('Card.lua', '    control._euiDependent = dependent\n', '', 'dependent flag not recorded'),
    ('Card.lua', '    if control._euiFill or opts.fill then', '    if opts.fill then', 'full-width control not stretched'),
    ('Card.lua', '    if control._euiFill or opts.fill then', '    if control._euiFill then', 'opts.fill ignored'),
    ('Card.lua', '    if #labelled > 0 then card._ctx:AlignLabelColumn(unpack(labelled)) end\n', '', 'card label column not aligned'),
    ('Card.lua', '    card._rows[#card._rows + 1] = row\n    layout(card, row)\n', '    card._rows[#card._rows + 1] = row\n', 'Add does not lay out'),
    ('Card.lua', '    card:SetHeight(card._top + math.max(1, h))', '    card:SetHeight(math.max(1, h))', 'card height forgets its label'),
    ('Card.lua', '    line:SetPoint("TOPLEFT", row, "BOTTOMLEFT")', '    line:SetPoint("TOPLEFT", row, "TOPLEFT")', 'divider at the top of the row'),

    # The color picker: its five contracts, the session state every addon shares, the Class
    # button, the swatch row, and the window that closes it. The Class button's own apply after
    # its reopen has no mutant: the transcribed picker commits the seeded color during the
    # reopen, so removing that call is invisible to every client the model describes.
    ('ColorPicker.lua', GATE, '', 'ColorPicker host check removed'),
    ('Context.lua', '    clear           = true,\n', '', 'clear label refused'),
    ('ColorPicker.lua', 'local state = lib.shared.colorPicker or {}', 'local state = {}', 'picker state rebuilt per copy'),
    ('ColorPicker.lua', 'lib.shared.colorPicker = state\n', '', 'picker state not shared'),
    ('ColorPicker.lua', 'local PROBE_ALPHA = 0.25', 'local PROBE_ALPHA = 0.5', 'probe at the ambiguous alpha'),
    ('ColorPicker.lua', '        if not _G.ColorPPBoxA then state.alphaInverted = false return end', '        if not _G.ColorPPBoxA then return end', 'a client with no box never settles'),
    ('ColorPicker.lua', '        if inverted ~= straight then\n            state.alphaInverted = inverted\n            return\n        end\n', '', 'an unambiguous reading still probes'),
    ('ColorPicker.lua', '        setControl(PROBE_ALPHA)', '        OpacitySliderFrame:SetValue(PROBE_ALPHA)', 'the probe commits'),
    ('ColorPicker.lua', '        if inverted ~= straight then state.alphaInverted = inverted end', '        state.alphaInverted = inverted', 'an ambiguous probe latches'),
    ('ColorPicker.lua', '        local inverted = math.abs(shown - (1 - na)) < 0.01', '        local inverted = math.abs(shown - na) < 0.01', 'opening reading compared the wrong way'),
    ('ColorPicker.lua', '        if state.alphaInverted ~= nil or not (hasAlpha and OpacitySliderFrame) then return end', '        if not (hasAlpha and OpacitySliderFrame) then return end', 'convention re-derived per open'),
    ('ColorPicker.lua', '        if state.alphaInverted then return 1 - v end\n', '', 'seed ignores the convention'),
    ('ColorPicker.lua', '        cp.opacityFunc = nil\n', '', 'seeding commits'),
    ('ColorPicker.lua', '        cp.opacityFunc = fn\n', '', 'opacity callback lost after seeding'),
    ('ColorPicker.lua', '        if hasAlpha and OpacitySliderFrame and OpacitySliderFrame:GetValue() ~= controlValue(na) then', '        if false then', 'first open never corrected'),
    ('ColorPicker.lua', '            setControl(controlValue(na))', '            OpacitySliderFrame:SetValue(controlValue(na))', 'the correction commits'),
    ('ColorPicker.lua', '        if cp:IsShown() then cp:Hide() end\n', '', 're-seed skips OnShow'),
    ('ColorPicker.lua', '                na = state.alphaInverted and (1 - raw) or raw', '                na = raw', 'stored alpha ignores the convention'),
    ('ColorPicker.lua', '        if hasAlpha then\n            local raw = rawAlpha()', '        if true then\n            local raw = rawAlpha()', 'a no-alpha picker reads the slider'),
    ('ColorPicker.lua', '        if onCancel then onCancel() else onChange(origR, origG, origB, origA) end', '        if onCancel then onCancel() end', 'cancel with no onCancel restores nothing'),
    ('ColorPicker.lua', '        if onCancel then onCancel() else onChange(origR, origG, origB, origA) end', '        onChange(origR, origG, origB, origA)', 'cancel ignores the caller'),
    ('ColorPicker.lua', '        if cp.SetupColorPickerAndShow then', '        if false then', 'modern entry point never used'),
    ('ColorPicker.lua', '            cp.func, cp.opacityFunc, cp.cancelFunc = apply, apply, cancel', '            cp.opacityFunc, cp.cancelFunc = apply, cancel', 'legacy picker gets no color callback'),
    ('ColorPicker.lua', '        state.apply, state.reopen, state.cancel, state.owner = nil, nil, nil, nil\n', '', 'a closed picker keeps its callbacks'),
    ('ColorPicker.lua', '    if state.hooked or not ColorPickerFrame then return end', '    if not ColorPickerFrame then return end', 'hook installed per open'),
    ('ColorPicker.lua', '        if state.classButton then state.classButton:Hide() end\n', '', 'Class button outlives the picker'),
    ('ColorPicker.lua', '    if elvUILoaded() or _G.ColorPPBoxA or not ColorPickerFrame then', '    if _G.ColorPPBoxA or not ColorPickerFrame then', 'second Class button beside ElvUI'),
    ('ColorPicker.lua', '    if elvUILoaded() or _G.ColorPPBoxA or not ColorPickerFrame then', '    if elvUILoaded() or not ColorPickerFrame then', 'second Class button beside a picker box'),
    ('ColorPicker.lua', '    if state.classButton ~= nil then return state.classButton or nil end\n', '', 'Class button built per open'),
    ('ColorPicker.lua', '        if not r then return end\n', '', 'Class button presses with no color'),
    ('ColorPicker.lua', '    if c then return c.r, c.g, c.b end', '    if c then return c.r, c.r, c.b end', 'class color green channel'),
    ('ColorPicker.lua', '    kit.Fill(ctx, b, "surface")\n', '', 'Class button has no fill'),
    ('ColorPicker.lua', '    b:SetPoint("TOPLEFT", ColorPickerFrame, "TOPRIGHT", 6, -34)', '    b:SetPoint("TOPLEFT", ColorPickerFrame, "TOPLEFT", 6, -34)', 'Class button placed over the picker'),
    ('ColorPicker.lua', '= apply, openWith, cancel, ctx._window', '= apply, openWith, cancel, nil', 'picker owner not recorded'),
    ('ColorPicker.lua', '        if classBtn then classBtn:Show() end\n', '', 'Class button never shown'),
    ('ColorPicker.lua', '    swatch:SetSize(sp.swatchWidth, sp.swatchHeight)', '    swatch:SetSize(44, 20)', 'swatch keeps the old size'),
    ('ColorPicker.lua', '    kit.Edge(self, swatch, "borderStrong")', '    kit.Edge(self, swatch, "divider")', 'swatch edge color'),
    ('ColorPicker.lua', '    underlay:SetColorTexture(0, 0, 0, 1)\n', '', 'no black underlay'),
    ('ColorPicker.lua', '            tex:SetColorTexture(c.r, c.g or 0, c.b or 0, c.a or 1)', '            tex:SetColorTexture(c.r, c.g or 0, c.b or 0, 1)', 'swatch drawn opaque'),
    ('ColorPicker.lua', '            tex:SetColorTexture(ctx:Color("track"))', '            tex:SetColorTexture(0, 0, 0, 1)', 'an unset swatch looks black'),
    ('ColorPicker.lua', '        local isSet = (c and c.r ~= nil) and true or false', '        local isSet = (c ~= nil) and true or false', 'an empty table counts as set'),
    ('ColorPicker.lua', '        if clear then clear:SetShown(isSet) end', '        if clear then clear:Show() end', 'Clear shown while unset'),
    ('ColorPicker.lua', '            onClear()\n            paint()', '            onClear()', 'Clear not repainted'),
    ('ColorPicker.lua', '        width = width + clear:GetWidth() + CLEAR_GAP\n', '', 'no room kept for Clear'),
    ('ColorPicker.lua', '        end, nil, "ghost")', '        end, nil, "secondary")', 'Clear outlined'),
    ('ColorPicker.lua', '    if onClear and not clearLabel then', '    if false then', 'Clear with no label accepted'),
    ('ColorPicker.lua', '        local prev = c and { r = c.r, g = c.g, b = c.b, a = c.a } or nil', '        local prev = c', 'previous color aliased'),
    ('ColorPicker.lua', '            setter(v)\n            paint()', '            setter(v)', 'swatch not repainted on commit'),
    ('ColorPicker.lua', '        if mouseButton == "LeftButton" then swatch:Click() end', '        swatch:Click()', 'any click on the row opens'),
    ('ColorPicker.lua', '    holder:EnableMouse(true)\n', '', 'row takes no mouse'),
    ('ColorPicker.lua', '    holder.Refresh = paint\n', '', 'picker has no Refresh'),
    ('ColorPicker.lua', '    holder._euiFill = true\n', '', 'picker row not stretched'),
    ('ColorPicker.lua', '    content._controls[#content._controls + 1] = holder\n', '', 'picker not registered'),
    ('ColorPicker.lua', '    swatch:SetPoint("RIGHT")\n', '    swatch:SetPoint("LEFT", text, "RIGHT", 8, 0)\n', 'swatch beside the label'),
    ('ColorPicker.lua', '    local width = (text:GetStringWidth() or 0) + CLEAR_GAP + sp.swatchWidth', '    local width = sp.swatchWidth', 'picker width ignores the label'),
    ('ColorPicker.lua', '        clear:SetPoint("RIGHT", swatch, "LEFT", -CLEAR_GAP, 0)', '        clear:SetPoint("LEFT", holder, "RIGHT", 8, 0)', 'Clear hung off the row end'),
    ('ColorPicker.lua', 'local CLEAR_GAP = 8', 'local CLEAR_GAP = 4', 'Clear gap'),
    ('Window.lua', '        if picker and picker.owner == f and ColorPickerFrame and ColorPickerFrame:IsShown() then', '        if picker and ColorPickerFrame and ColorPickerFrame:IsShown() then', "window cancels another addon's picker"),
    ('Window.lua', '            if cancelPending then cancelPending() end\n', '', 'window hides its picker without cancelling'),
    ('Window.lua', '            local cancelPending = picker.cancel\n            ColorPickerFrame:Hide()\n', '            ColorPickerFrame:Hide()\n            local cancelPending = picker.cancel\n', 'cancel read after the hide clears it'),
    ('Window.lua', '        local picker = lib.shared.colorPicker\n', '        local picker = nil\n', 'window never closes its picker'),

    # Sized again once on screen: text measured while a tab was built came out short in game
    ('Kit.lua', '    for _, card in ipairs(frame._euiCards or {}) do card:Layout() end\n', '', 'Refit skips cards'),
    ('Kit.lua', '    for _, b in ipairs(frame._euiFit or {}) do b:Fit() end\n', '', 'Refit skips buttons'),
    ('Card.lua', '    content._euiCards = cards\n', '', 'card not listed on its content'),
    ('Controls.lua', '        content._euiFit = fits\n', '', 'button not listed on its parent'),
    ('Controls.lua', '        b.Fit = fit\n', '', 'button has no Fit'),
    ('Controls.lua', '    if width then\n        b:SetWidth(width)\n    else', '    if false then\n    else', 'a given width is ignored'),
    ('Controls.lua', '        kit.Refit(content)\n', '', 'MeasureContent never sizes again'),
    ('Window.lua', '    if footer then C_Timer.After(0, function() kit.Refit(footer) end) end\n', '', 'footer never sized again'),
    ('Window.lua', '            if t.id == self._current and t._built then settle(self, t) end\n', '', 'a scale change never sizes the tab again'),
    ('Window.lua', '    if f:IsShown() then\n        for _, t in ipairs(self._tabs or {}) do', '    if true then\n        for _, t in ipairs(self._tabs or {}) do', 'sized again while hidden'),

    # Wrapped text: a text block, rows sized to it, and two-column text rows
    ('Controls.lua', '    fs:SetWordWrap(true)\n', '    fs:SetWordWrap(false)\n', 'block line does not wrap'),
    ('Controls.lua', '        if i > 1 then y = y + (line.gap or TEXT_GAP) end', '        if i > 1 then y = y + TEXT_GAP end', 'line gap ignored'),
    ('Controls.lua', 'local TEXT_GAP = 4', 'local TEXT_GAP = 2', 'line gap'),
    ('Controls.lua', '        local x = line.indent + (line.bullet and BULLET_INDENT or 0)', '        local x = line.indent', 'bulleted text not moved past its bullet'),
    ('Controls.lua', '            line.bullet:SetPoint("TOPLEFT", block, "TOPLEFT", line.indent, -y)', '            line.bullet:SetPoint("TOPLEFT", block, "TOPLEFT", 0, -y)', 'bullet ignores the indent'),
    ('Controls.lua', '        line.fs:SetPoint("TOPRIGHT", block, "TOPRIGHT", 0, -y)\n', '', 'line not bounded by the block, so it never wraps'),
    ('Controls.lua', '        if not h or h <= 0 then h = line.size end', '        if not h then h = line.size end', 'an unmeasured line takes no height'),
    ('Controls.lua', "                   size = lib.tokens.typography[style].size }", "                   size = 12 }", "an unmeasured line ignores its style's size"),
    ('Controls.lua', '    block:SetHeight(math.max(1, y))\n', '', 'block height never set'),
    ('Controls.lua', '    measureBlock(block)\n    return fs', '    return fs', 'AddLine leaves the block unmeasured'),
    ('Controls.lua', '    block._euiFill = true\n', '', 'block not stretched across its row'),
    ('Controls.lua', '    local fs = kit.Text(ctx, block, style, opts.color)', '    local fs = kit.Text(ctx, block, style)', 'line color ignored'),
    ('Controls.lua', '        line.bullet = kit.Text(ctx, block, style, opts.color)', '        line.bullet = kit.Text(ctx, block, "hint")', "bullet not in its line's style"),
    ('Controls.lua', '    style = style or "label"', '    style = style or "value"', 'a line with no style is not a label'),
    ('Controls.lua', '        value:SetPoint("LEFT", holder, "LEFT", columnEdge(label, w), 0)', '        value:SetPoint("LEFT", holder, "LEFT", w, 0)', 'text row ignores the control gap'),
    ('Controls.lua', '    holder:SetLabelWidth(lib.tokens.spacing.labelColumn)\n', '', 'text row starts with no column'),
    ('Controls.lua', '    value:SetPoint("RIGHT")\n    value:SetWordWrap(false)\n', '    value:SetWordWrap(false)\n', "text row's text not bounded at the row's end"),
    ('Controls.lua', '    value:SetWordWrap(false)\n    value:SetText(text or "")', '    value:SetWordWrap(true)\n    value:SetText(text or "")', "text row's text wraps"),
    ('Controls.lua', '    holder.text = value\n', '', "text row's text not exposed"),
    ('Card.lua', '                row:SetHeight(row.control:Measure() + TEXT_PADDING * 2)\n', '', 'fitHeight row never measured'),
    ('Card.lua', '            if row.fitHeight and (not added or row == added) then', '            if row.fitHeight then', 'Add measures every fitted row again'),
    ('Card.lua', '            if row.fitHeight and (not added or row == added) then', '            if row.fitHeight and row == added then', 'Layout never measures fitted rows again'),
    ('Card.lua', '    layout(card, row)\n    return row', '    layout(card)\n    return row', 'Add lays out as a full Layout'),
    ('Card.lua', 'local TEXT_PADDING = 12', 'local TEXT_PADDING = 10', 'fitted row padding'),
    ('Card.lua', '    row.fitHeight = opts.fitHeight and true or false\n', '', 'fitHeight ignored'),
    ('Card.lua', '    if opts.fitHeight and not control.Measure then', '    if false then', 'fitHeight without Measure accepted'),
    ('Card.lua', '        error("EverythingUI: a fitHeight row needs a control with a Measure method", 2)', '        error("EverythingUI: a fitHeight row needs a control with a Measure method", 1)', 'fitHeight error points at the library'),
    ('Tokens.lua', 'listRowHeight      = 28', 'listRowHeight      = 30', 'list row height'),

    # The preview panel
    ('Window.lua', '    preview = "function", previewRefresh = "function",\n', '', 'a tab with a preview is refused'),
    ('Window.lua', '    if def.previewRefresh and not def.preview then', '    if false then', 'previewRefresh with no preview accepted'),
    ('Window.lua', '        local side = t.preview and sp.previewWidth or 0', '        local side = sp.previewWidth', 'every tab narrows for a preview'),
    ('Window.lua', '        content:SetWidth(width - side)', '        content:SetWidth(width)', 'the column keeps its width under the panel'),
    ('Window.lua', '        scroll:SetPoint("BOTTOMRIGHT", -(sp.contentSides + side), 0)', '        scroll:SetPoint("BOTTOMRIGHT", -sp.contentSides, 0)', 'the scroll area runs under the panel'),
    ('Window.lua', '        bar:SetPoint("TOPRIGHT", -(SCROLLBAR_INSET + side), -sp.contentTop)', '        bar:SetPoint("TOPRIGHT", -SCROLLBAR_INSET, -sp.contentTop)', 'the scroll bar sits on the panel'),
    ('Window.lua', '            local panel = CreateFrame("Frame", nil, holder)', '            local panel = CreateFrame("Frame", nil, area)', 'the panel outlives its tab'),
    ('Window.lua', '            panel:SetWidth(side)', '            panel:SetWidth(300)', 'panel width'),
    ('Window.lua', '            kit.Fill(ctx, panel, "chrome")', '            kit.Fill(ctx, panel, "surface")', 'panel not on the chrome fill'),
    ('Window.lua', '            kit.Edge(ctx, panel, "divider", "L")', '            kit.Edge(ctx, panel, "divider", "R")', 'panel divider on the wrong side'),
    ('Window.lua', '                    t._previewBuilt = true\n', '', 'the preview is built again on every view'),
    ('Window.lua', '                if t.previewRefresh then t.previewRefresh(self, t._preview) end\n', '', 'the preview is never refreshed'),
    ('Tokens.lua', 'previewWidth       = 320', 'previewWidth       = 300', 'preview width'),

    # A tooltip opens in one place, centered over the column just above its control
    ('Kit.lua', '        tip:SetOwner(owner, "ANCHOR_NONE")', '        tip:SetOwner(owner, "ANCHOR_RIGHT")', 'tooltip back beside its owner'),
    ('Kit.lua', '        tip:ClearAllPoints()\n', '', 'tooltip anchors pile up'),
    ('Kit.lua', '        if column and column._controls then', '        if column then', 'a footer button centers on the footer, not itself'),
    ('Kit.lua', '        if column and column._controls then', '        if false then', 'a tooltip centers on its control, not the column'),
    ('Kit.lua', 'then dx = (cx - ox) * owner:GetEffectiveScale() / tip:GetEffectiveScale() end', 'then dx = cx - ox end', "the offset ignores the window's scale"),
    ('Kit.lua', 'then dx = (cx - ox) * owner:GetEffectiveScale() / tip:GetEffectiveScale() end', 'then dx = (ox - cx) * owner:GetEffectiveScale() / tip:GetEffectiveScale() end', 'the offset runs the wrong way'),
    ('Kit.lua', '        tip:SetPoint("BOTTOM", owner, "TOP", dx, TIP_GAP)', '        tip:SetPoint("BOTTOM", owner, "TOP", 0, TIP_GAP)', 'the centering offset is dropped'),
    ('Kit.lua', '        tip:SetPoint("BOTTOM", owner, "TOP", dx, TIP_GAP)', '        tip:SetPoint("TOP", owner, "BOTTOM", dx, -TIP_GAP)', 'the tooltip opens below its control'),
    ('Kit.lua', 'local TIP_GAP = 4', 'local TIP_GAP = 0', 'tooltip gap'),
    ('Kit.lua', '        tip:SetOwner(owner, anchor)\n', '        tip:SetOwner(owner, "ANCHOR_TOP")\n', 'a caller anchor is ignored'),
    ('Controls.lua', '        t:HookScript("OnEnter", function() kit.ShowTip(getTip, anchor, title, body) end)', '        t:HookScript("OnEnter", function(s) kit.ShowTip(getTip, s, title, body) end)', 'a slider opens its tooltip in two places'),
    ('Dropdown.lua', 'kit.ShowTip(getTip, s, title, body, "ANCHOR_RIGHT")', 'kit.ShowTip(getTip, s, title, body)', 'list tips cover the other options'),

    # The dialog, moved from EQOT with its 1.28 rules
    ('Dialog.lua', GATE, '', 'Dialog host check removed'),
    ('Dialog.lua', '    if not opts then return end\n', '', 'a double fire runs the callback twice'),
    ('Dialog.lua', '    f.opts = nil\n', '', 'a finished dialog never closes'),
    ('Dialog.lua', '    f.edit:ClearFocus()\n', '', 'the field keeps the keyboard while the callback runs'),
    ('Dialog.lua', '    f.edit:ClearFocus()\n', '    f.edit:ClearFocus()\n    f:Hide()\n', 'the dialog hides before the callback, which blocked ReloadUI on retail'),
    ('Dialog.lua', '    if not f.opts then f:Hide() end\n', '    f:Hide()\n', 'a callback that opens the next dialog has it hidden'),
    ('Dialog.lua', '        if opts.onAccept then xpcall(function() opts.onAccept(text) end, geterrorhandler()) end', '        if opts.onAccept then opts.onAccept(text) end', 'a raising callback leaves the dialog on screen'),
    ('Dialog.lua', '        xpcall(opts.onCancel, geterrorhandler())', '        opts.onCancel()', 'a raising Cancel leaves the dialog on screen'),
    ('Dialog.lua', '    elseif opts.onCancel then', '    elseif false then', 'Cancel no longer reaches its callback'),
    ('Dialog.lua', 'opts.onAccept(text) end, geterrorhandler()) end', 'opts.onAccept() end, geterrorhandler()) end', 'what was typed never reaches onAccept'),
    ('Dialog.lua', '    local text = f.edit:IsShown() and f.edit:GetText() or nil', '    local text = f.edit:GetText()', 'a dialog with no field hands onAccept stale text'),
    ('Dialog.lua', '    edit:SetScript("OnEnterPressed", function() finish(f, true) end)', '    edit:SetScript("OnEnterPressed", function() finish(f, false) end)', 'Enter in the field cancels'),
    ('Dialog.lua', '    edit:SetScript("OnEscapePressed", function() finish(f, false) end)', '    edit:SetScript("OnEscapePressed", function() finish(f, true) end)', 'Escape in the field accepts'),
    ('Dialog.lua', '            f:SetPropagateKeyboardInput(false)\n            finish(f, false)', '            f:SetPropagateKeyboardInput(false)\n            finish(f, true)', 'Escape accepts, which reloads on a reload prompt'),
    ('Dialog.lua', '            f:SetPropagateKeyboardInput(false)\n        else', '            finish(f, true)\n        else', 'Enter with no field accepts, which reloads on a reload prompt'),
    ('Dialog.lua', '        elseif (key == "ENTER" or key == "NUMPADENTER") and not f.edit:IsShown() then', '        elseif key == "ENTER" and not f.edit:IsShown() then', "the keypad's Enter reaches the game"),
    ('Dialog.lua', '        else\n            f:SetPropagateKeyboardInput(true)\n        end', '        end', 'other keys are kept from the game'),
    ('Dialog.lua', '        if InCombatLockdown() then return end\n        if key == "ESCAPE" then', '        if key == "ESCAPE" then', 'a key in combat makes the protected call'),
    ('Dialog.lua', '    if f.opts then finish(f, false) end\n', '', 'a dialog opened over another drops it silently'),
    ('Dialog.lua', '    if f.opts then finish(f, false) end\n', '    if f.opts then finish(f, true) end\n', 'a dialog opened over another accepts it'),
    ('Dialog.lua', '        if InCombatLockdown() then\n            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n            return\n        end\n        arm()', '        arm()', 'a dialog opened in combat stays keyboard-dead after it'),
    ('Dialog.lua', '            f:UnregisterEvent("PLAYER_REGEN_ENABLED")\n            arm()', '            arm()', 'the combat wait never ends'),
    ('Dialog.lua', '        elseif event == "PLAYER_REGEN_ENABLED" then', '        else', 'any event ends the combat wait'),
    ('Dialog.lua', '    f:HookScript("OnHide", function()\n        f:EnableKeyboard(false)\n', '    f:HookScript("OnHide", function()\n', 'the dialog keeps the keyboard after it closes'),
    ('Dialog.lua', '        f:EnableKeyboard(false)\n        f:UnregisterEvent("PLAYER_REGEN_ENABLED")\n', '        f:EnableKeyboard(false)\n', 'a dialog closed while waiting keeps waiting'),
    ('Dialog.lua', '    f:SetFrameStrata("FULLSCREEN_DIALOG")', '    f:SetFrameStrata("DIALOG")', 'the dialog sits under the settings window'),
    ('Dialog.lua', '    f:SetClampedToScreen(true)\n', '', 'dialog not clamped'),
    ('Dialog.lua', '    kit.Fill(ctx, f, "surface")', '    kit.Fill(ctx, f, "chrome")', 'dialog fill'),
    ('Dialog.lua', '    f.title = kit.Text(ctx, f, "title")', '    f.title = kit.Text(ctx, f, "label")', 'dialog title style'),
    ('Dialog.lua', '    f.body:SetWordWrap(true)\n', '', 'dialog text does not wrap'),
    ('Dialog.lua', 'function() finish(f, true) end, nil, "primary")', 'function() finish(f, true) end, nil)', 'the first button is not primary'),
    ('Dialog.lua', '        f.cancel:Hide()\n', '', 'a one-button dialog keeps the secondary'),
    ('Dialog.lua', '        f.cancel:Show()\n', '', 'the secondary never comes back'),
    ('Dialog.lua', '    edit:SetFontObject(GameFontHighlight)\n', '', "the field ignores the client's font"),
    ('Dialog.lua', '        edit:SetFocus()\n        -- After SetFocus, which clears any selection of its own.\n        if opts.highlightEditBox then edit:HighlightText() end', '        if opts.highlightEditBox then edit:HighlightText() end\n        edit:SetFocus()', 'a link opens unselected'),
    ('Dialog.lua', '        edit:SetMaxLetters(opts.maxLetters or 0)\n', '', 'the letter limit is lost'),
    ('Dialog.lua', '    C_Timer.After(0, function() if f:IsShown() then layout(f) end end)\n', '', 'text measured hidden is never sized again'),
    ('Dialog.lua', '    C_Timer.After(0, function() if f:IsShown() then layout(f) end end)', '    C_Timer.After(0, function() layout(f) end)', 'a closed dialog is sized again'),
    ('Dialog.lua', '    if not h or h <= 0 then h = lib.tokens.typography[style].size end', '    if not h then h = lib.tokens.typography[style].size end', 'an unmeasured dialog line takes no height'),
    ('Dialog.lua', '    f.accept:Fit()\n', '', 'the primary is not sized to its label'),
    ('Dialog.lua', '                + (f.edit:IsShown() and (FIELD_GAP + sp.fieldHeight) or 0)\n', '', 'the dialog does not grow for its field'),
    ('Dialog.lua', '        error("EverythingUI: ShowDialog needs title, text and button1", 2)', '        error("EverythingUI: ShowDialog needs title, text and button1", 1)', 'ShowDialog error points at the library'),
    ('Dialog.lua', '        if DIALOG_FIELDS[key] ~= type(v) then', '        if false then', 'a misspelled dialog field is accepted'),
    ('Dialog.lua', '    if not f then\n        f = build(self)\n        self._dialog = f\n    end', '    f = build(self)\n    self._dialog = f', 'a new dialog every time'),
    ('Dialog.lua', '    f:Raise()\n', '', 'the dialog is not raised'),
    # MINOR 15, from the pre-release scan. Three removals have no mutant because they are EQUIVALENT:
    # the menu's and the field's ClearAllPoints before re-anchoring, since each only ever sets points
    # of the same names and the client replaces a point of a name already set; and the Unregister
    # right after the menu's event probe, since the menu is built inside its first ShowMenu, whose
    # Show registers the event again the same moment.
    ('Menu.lua', '    if pcall(m.RegisterEvent, m, "GLOBAL_MOUSE_DOWN") then', '    if false then', 'menu catcher used where the event exists'),
    ('Menu.lua', '    if pcall(m.RegisterEvent, m, "GLOBAL_MOUSE_DOWN") then', '    if true then', 'menu listens for an event the client refused'),
    ('Menu.lua', '            if not self:IsMouseOver() then self:Hide() end', '            self:Hide()', 'a press on the menu closes it'),
    ('Menu.lua', '        m:SetScript("OnEvent", function(self)\n', '        m:SetScript("OnShow_", function(self)\n', 'a press elsewhere never closes it'),
    ('Menu.lua', '        m:HookScript("OnShow", function(self) self:RegisterEvent("GLOBAL_MOUSE_DOWN") end)\n', '', 'menu never listens'),
    ('Menu.lua', '        m:HookScript("OnHide", function(self) self:UnregisterEvent("GLOBAL_MOUSE_DOWN") end)\n', '', 'menu listens after it closes'),
    ('Dialog.lua', '        f:RegisterEvent("PLAYER_REGEN_DISABLED")\n        -- Deferred', '        -- Deferred', 'dialog never hears combat start'),
    ('Dialog.lua', '        if event == "PLAYER_REGEN_DISABLED" then', '        if false then', 'combat start ignored'),
    ('Dialog.lua', '            f:EnableKeyboard(false)\n            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n', '            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n', 'dialog keeps the keyboard into combat'),
    ('Dialog.lua', '            f:EnableKeyboard(false)\n            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n', '            f:EnableKeyboard(false)\n', 'dialog never takes the keyboard back after combat'),
    ('Dialog.lua', '        f:UnregisterEvent("PLAYER_REGEN_DISABLED")\n    end)', '    end)', 'closed dialog keeps listening for combat'),
    ('Dialog.lua', '    local useData = kit.NeedsClientFont(opts.text)', '    local useData = false', 'dialog client font never used'),
    ('Dialog.lua', '    local useData = kit.NeedsClientFont(opts.text)', '    local useData = true', 'dialog client font used for every text'),
    ('Dialog.lua', '    f.body:SetShown(not useData)\n', '', 'Barlow body left up beside the client-font one'),
    ('Dialog.lua', '    f.bodyData:SetShown(useData)\n', '', 'client-font body never shown'),
    ('Dialog.lua', '    f.shownBody = useData and f.bodyData or f.body', '    f.shownBody = f.body', 'field and height follow the hidden body'),
    ('Dialog.lua', '    f.bodyData:SetTextColor(ctx:Color("label"))\n', '', 'client-font body not in the label color'),
    ('Dialog.lua', '    f.bodyData:SetWordWrap(true)\n', '', 'client-font body does not wrap'),
    ('Dialog.lua', '    f.bodyData:SetPoint("TOPRIGHT", f.title, "BOTTOMRIGHT", 0, -TEXT_GAP)\n', '', 'client-font body unbounded'),
    ('Dialog.lua', '    edit:SetPoint("TOPRIGHT", f.shownBody, "BOTTOMRIGHT", 0, -FIELD_GAP)\n', '', 'field has no right edge'),

    # Hand-breaks from the pre-release scan that the tests missed, each now caught.
    ('Window.lua', '        b:SetScript("OnClick", function() ctx:SelectTab(id) end)', '        b:SetScript("OnClick", function() end)', 'nav item click does nothing'),
    ('Window.lua', '        self:ApplyWindowScale()\n        self:SelectTab(self._current)', '        self:SelectTab(self._current)', 'opening ignores the saved window scale'),
    ('Window.lua', '    f:SetScript("OnDragStart", f.StartMoving)\n', '', 'settings window cannot be dragged'),
    ('Window.lua', '    title:SetText(opts.title)\n', '', 'header title blank'),
    ('Window.lua', '    version:SetText("v" .. opts.version)', '    version:SetText("")', 'header version blank'),
    ('Window.lua', '        holder:SetAllPoints()\n', '', 'tab holder has no size'),
    ('Window.lua', '        scroll:SetPoint("TOPLEFT", sp.contentSides, -sp.contentTop)\n', '', 'tab scroll area has no top-left'),
    ('Window.lua', '        f:ClearAllPoints()\n', '', 'a dragged window keeps its old anchor beside the center'),
    ('Dialog.lua', '        f.cancel:SetText(opts.button2)', '        f.cancel:SetText("Cancel")', 'the secondary ignores button2'),
    ('Dialog.lua', '    f:SetScript("OnDragStart", f.StartMoving)\n', '', 'dialog cannot be dragged'),
    ('Dialog.lua', '    f.title:SetWordWrap(true)\n', '', 'dialog title does not wrap'),
    ('Dialog.lua', '    kit.Edge(ctx, edit, "inputBorder")\n', '', 'dialog field has no border'),
    ('Menu.lua', '    b.line:SetPoint("LEFT")\n    b.line:SetPoint("RIGHT")\n', '', 'menu divider line has no width'),
    ('Controls.lua', '    track:SetPoint("RIGHT")\n', '', 'slider track has no right edge'),
    ('Dropdown.lua', '    p:SetHeight(h)\n    p:ClearAllPoints()\n', '    p:SetHeight(h)\n', 'list keeps its old anchors when it flips above'),

    # MINOR 16, from the second scan. The client font is decided per character against Barlow's own
    # coverage. Three removals there have no mutant because they are EQUIVALENT: letting the overlong
    # leads 0xC0 and 0xC1 through (they decode below 0x80, which is in no range), dropping the four-byte
    # branch (such a lead then falls to the not-well-formed branch, which answers the same), and a
    # stray 0x80 read as a character (0x80 is in no range either).
    ('Kit.lua', '            if not barlowDraws(cp) then return true end', '            if false then return true end', 'client font never used for a character Barlow lacks'),
    ('Kit.lua', '            if not barlowDraws(cp) then return true end', '            return true', 'every character past ASCII goes to the client font'),
    ('Kit.lua', '0x2013, 0x2014,', '0x2013, 0x2013,', 'the em dash left out of Barlow'),
    ('Kit.lua', '        if cp < BARLOW[mid * 2 - 1] then', '        if cp <= BARLOW[mid * 2 - 1] then', 'a range start counted outside it'),
    ('Kit.lua', '        elseif cp > BARLOW[mid * 2] then', '        elseif cp >= BARLOW[mid * 2] then', 'a range end counted outside it'),
    ('Kit.lua', '                cp = cp * 64 + (c - 0x80)', '                cp = cp * 64 + c', 'continuation bytes decoded wrong'),
    ('Kit.lua', '                if not c or c < 0x80 or c > 0xBF then return true end', '                if not c then return true end', 'a broken sequence read as a character'),
    ('Kit.lua', '            else\n                return true\n            end\n            for k = 1, len - 1 do', '            else\n                len, cp = 1, b\n            end\n            for k = 1, len - 1 do', 'a stray byte read as a character'),
    ('Kit.lua', '                len, cp = 3, b - 0xE0', '                len, cp = 3, b - 0xD0', 'three-byte characters decoded wrong'),
    ('Kit.lua', '            i = i + len\n', '            i = i + 1\n', 'a character read again from its second byte'),
    ('Menu.lua', '            if not self:IsMouseOver() then self:Hide() end', '            if not InCombatLockdown() and not self:IsMouseOver() then self:Hide() end', 'a click elsewhere in combat leaves the menu open'),
    ('Menu.lua', '        m:HookScript("OnShow", function(self) self:RegisterEvent("GLOBAL_MOUSE_DOWN") end)', '        m:HookScript("OnShow", function(self) if not InCombatLockdown() then self:RegisterEvent("GLOBAL_MOUSE_DOWN") end end)', 'a menu opened in combat never listens'),
    ('Menu.lua', '    b.data = kit.DataText(b)\n', '    b.data = kit.DataText(b)\n    kit.Style(ctx, b.data, "label")\n', 'menu client-font string given Barlow'),
    ('Dialog.lua', '        f:RegisterEvent("PLAYER_REGEN_DISABLED")\n        -- Deferred', '        if not f._heard then f:RegisterEvent("PLAYER_REGEN_DISABLED") f._heard = true end\n        -- Deferred', 'combat start heard on the first show only'),
    ('Dialog.lua', '            return\n        end\n        arm()\n    end)', '            f:UnregisterEvent("PLAYER_REGEN_DISABLED")\n            return\n        end\n        arm()\n    end)', 'combat start not heard on a dialog opened in combat'),
    ('Dialog.lua', '            f:UnregisterEvent("PLAYER_REGEN_ENABLED")\n            arm()', '            f:UnregisterEvent("PLAYER_REGEN_ENABLED")\n            f:UnregisterEvent("PLAYER_REGEN_DISABLED")\n            arm()', 'the end of a fight stops it hearing the next'),
    ('Dialog.lua', '            f:EnableKeyboard(false)\n            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n', '            f:EnableKeyboard(false)\n            f:UnregisterEvent("PLAYER_REGEN_DISABLED")\n            f:RegisterEvent("PLAYER_REGEN_ENABLED")\n', 'combat start heard once per show'),
    ('Dialog.lua', '    local useData = kit.NeedsClientFont(opts.text)', '    local useData = opts.hasEditBox == true and kit.NeedsClientFont(opts.text)', 'client font only on a dialog with a field'),
    ('Dialog.lua', '    f.bodyData:SetText(opts.text)\n', '    if not f.bodyData:GetText() then f.bodyData:SetText(opts.text) end\n', 'client-font body keeps its first text'),
    ('Dialog.lua', '    f.bodyData = kit.DataText(f)\n', '    f.bodyData = kit.DataText(f)\n    kit.Style(ctx, f.bodyData, "label")\n', 'client-font body given Barlow'),
    ('Controls.lua', '        t:ClearAllPoints()\n        t:SetPoint("CENTER")', '        t:SetPoint("CENTER")', 'icon keeps the fill anchors beside its center'),
    ('Controls.lua', '        row[2]:ClearAllPoints()\n', '', 'satellite keeps its old anchor'),
    ('Controls.lua', '        p.button:ClearAllPoints()\n', '', 'swatch keeps its old anchor'),
    ('Controls.lua', '        p.label:ClearAllPoints()\n', '', 'picker label keeps its old anchor'),
    ('Window.lua', '        d.text:ClearAllPoints()\n', '', 'Discord text keeps its center anchor'),

    # The context menu, one for every addon. The closer's own Hide at build has no mutant: the
    # menu is built inside its first ShowMenu, whose Show puts the closer up the same moment.
    ('Menu.lua', GATE, '', 'Menu host check removed'),
    ('EverythingUI.xml', '    <Script file="Menu.lua"/>\n', '', 'Menu.lua not loaded'),
    ('Tokens.lua', 'danger        = hex("FF5050")', 'danger        = hex("FF5151")', 'danger red off by one'),
    ('Tokens.lua', 'menuItemHeight     = 24', 'menuItemHeight     = 22', 'menu item height'),
    ('Menu.lua', '    if shared.menu then return shared.menu end\n', '', 'a new menu per open'),
    ('Menu.lua', '    shared.menu = m\n', '', 'menu not shared'),
    ('Menu.lua', '    m:SetFrameStrata("FULLSCREEN_DIALOG")', '    m:SetFrameStrata("DIALOG")', 'the menu sits under the settings window'),
    ('Menu.lua', '    m:SetClampedToScreen(true)\n', '', 'menu not clamped'),
    ('Menu.lua', '    m:EnableMouse(true)\n', '', 'a click on the padding reaches the closer'),
    ('Menu.lua', '    m:EnableMouse(true)\n    m:Hide()\n', '    m:EnableMouse(true)\n', 'the menu is born shown, so its first open arms nothing'),
    ('Menu.lua', '    kit.Fill(ctx, m, "surface")', '    kit.Fill(ctx, m, "chrome")', 'menu fill'),
    ('Menu.lua', '    m.edges = kit.Edge(ctx, m, "surfaceBorder")', '    m.edges = kit.Edge(ctx, m, "divider")', 'menu edge color'),
    ('Menu.lua', '    kit.CloseOnEscape(m)\n', '', 'Escape does not close the menu'),
    ('Menu.lua', '    closer:SetAllPoints(UIParent)\n', '', 'the closer covers nothing'),
    ('Menu.lua', '    closer:SetFrameStrata("FULLSCREEN")', '    closer:SetFrameStrata("TOOLTIP")', 'the closer covers the menu'),
    ('Menu.lua', '    closer:RegisterForClicks("AnyDown")', '    closer:RegisterForClicks("LeftButtonUp")', 'only a left release closes it'),
    ('Menu.lua', '    closer:SetScript("OnClick", function() m:Hide() end)\n', '', 'a click elsewhere does nothing'),
    ('Menu.lua', '    m:HookScript("OnShow", function() closer:Show() end)\n', '', 'outside click not caught'),
    ('Menu.lua', '    m:HookScript("OnHide", function() closer:Hide() end)\n', '', 'the closer outlives the menu'),
    ('Menu.lua', '    if b._onClick then xpcall(b._onClick, geterrorhandler()) end\n    -- An action that opened the next menu keeps it up.\n    if m.gen == gen then m:Hide() end', '    m:Hide()\n    if b._onClick then xpcall(b._onClick, geterrorhandler()) end', 'the action runs after the menu hides'),
    ('Menu.lua', '    if b._onClick then xpcall(b._onClick, geterrorhandler()) end', '    if b._onClick then b._onClick() end', 'a raising action leaves the menu up'),
    ('Menu.lua', '    if m.gen == gen then m:Hide() end', '    m:Hide()', 'an action that opens the next menu has it closed'),
    ('Menu.lua', '    if m.gen == gen then m:Hide() end', '', 'a click never closes the menu'),
    ('Menu.lua', '    m.gen = m.gen + 1\n', '', 'an open is not counted'),
    ('Menu.lua', '    b._onClick = item.onClick\n', '', 'a row never takes its action'),
    ('Menu.lua', '    b._kind = kind\n', '', 'row kind not recorded'),
    ('Menu.lua', '    b:SetHeight(kind == "divider" and DIVIDER_SLOT or lib.tokens.spacing.menuItemHeight)', '    b:SetHeight(lib.tokens.spacing.menuItemHeight)', 'a divider takes a full row'),
    ('Menu.lua', 'local DIVIDER_SLOT = 9', 'local DIVIDER_SLOT = 8', 'divider slot'),
    ('Menu.lua', '    b:EnableMouse(kind == nil)', '    b:EnableMouse(true)', 'a title or divider is clickable'),
    ('Menu.lua', '    b:EnableMouse(kind == nil)', '    b:EnableMouse(kind ~= "divider")', 'a title is clickable'),
    ('Menu.lua', '    b.line:SetShown(kind == "divider")', '    b.line:Show()', 'every row carries a line'),
    ('Menu.lua', '    b.line:SetShown(kind == "divider")', '    if kind == "divider" then b.line:Show() end', 'a divider row reused keeps its line'),
    ('Menu.lua', '        b.text:Hide()\n        b.data:Hide()\n        return', '        return', 'a divider row reused keeps its text'),
    ('Menu.lua', '    local color = (kind == "title" and "muted") or (item.danger and "danger") or "text"', '    local color = (item.danger and "danger") or "text"', 'title not muted'),
    ('Menu.lua', '    local color = (kind == "title" and "muted") or (item.danger and "danger") or "text"', '    local color = (kind == "title" and "muted") or "text"', 'danger ignored'),
    ('Menu.lua', '    local color = (kind == "title" and "muted") or (item.danger and "danger") or "text"', '    local color = (kind == "title" and "muted") or (item.danger and "danger") or "label"', 'items in the label color'),
    ('Menu.lua', '    kit.Style(ctx, b.text, kind == "title" and "groupLabel" or "label", color)', '    kit.Style(ctx, b.text, "label", color)', 'title in the item style'),
    ('Menu.lua', '    kit.Style(ctx, b.text, kind == "title" and "groupLabel" or "label", color)', '    b.text:SetTextColor(ctx:Color(color))', 'a reused row keeps its old font'),
    ('Menu.lua', '    b.data:SetTextColor(ctx:Color(color))\n', '', 'client-font text not colored'),
    ('Menu.lua', '    local useData = kit.NeedsClientFont(item.text)', '    local useData = false', 'menu client font never used'),
    ('Menu.lua', '    local useData = kit.NeedsClientFont(item.text)', '    local useData = true', 'menu client font used for every string'),
    ('Menu.lua', '        fs:SetWordWrap(false)\n', '', 'a long title wraps'),
    ('Menu.lua', '        fs:SetPoint("LEFT", PAD, 0)', '        fs:SetPoint("LEFT", 0, 0)', 'menu text against the edge'),
    ('Menu.lua', 'local PAD = 12', 'local PAD = 10', 'menu text inset'),
    ('Menu.lua', '        paint(self, b, items[i])\n        b:Show()\n', '        paint(self, b, items[i])\n', 'a row put away never comes back'),
    ('Menu.lua', '    for i = #items + 1, #m.rows do m.rows[i]:Hide() end\n', '', 'rows past the menu left shown'),
    ('Menu.lua', '        y = y + b:GetHeight()\n', '', 'menu rows not stacked'),
    ('Menu.lua', '        b:SetPoint("TOPLEFT", m, "TOPLEFT", 1, -y)', '        b:SetPoint("TOPLEFT", m, "TOPLEFT", 0, -y)', 'a row paints over the left edge'),
    ('Menu.lua', '    m:SetHeight(y + INSET)', '    m:SetHeight(y)', 'no inset under the last row'),
    ('Menu.lua', 'local INSET = 4', 'local INSET = 2', 'menu inset'),
    ('Menu.lua', 'local MIN_WIDTH = 160', 'local MIN_WIDTH = 150', 'menu minimum width'),
    ('Menu.lua', 'local MAX_WIDTH = 320', 'local MAX_WIDTH = 300', 'menu maximum width'),
    ('Menu.lua', '    m:SetWidth(math.min(MAX_WIDTH, math.max(MIN_WIDTH, widest + PAD * 2 + 2)))', '    m:SetWidth(math.max(MIN_WIDTH, widest + PAD * 2 + 2))', 'no maximum width'),
    ('Menu.lua', '    m:SetWidth(math.min(MAX_WIDTH, math.max(MIN_WIDTH, widest + PAD * 2 + 2)))', '    m:SetWidth(math.min(MAX_WIDTH, widest + PAD * 2 + 2))', 'no minimum width'),
    ('Menu.lua', '            if w > widest then widest = w end', '            widest = w', 'menu width follows the last row'),
    ('Menu.lua', '            local fs = b.data:IsShown() and b.data or b.text', '            local fs = b.text', 'menu width read off the hidden string'),
    ('Menu.lua', '        if b._kind ~= "divider" then', '        if true then', 'a divider row measured'),
    ('Menu.lua', '    m:SetPoint("TOPLEFT", UIParent, "BOTTOMLEFT", x / scale, y / scale)', '    m:SetPoint("TOPLEFT", UIParent, "BOTTOMLEFT", x, y)', 'the cursor read at the wrong scale'),
    ('Menu.lua', '    if tip then tip:Hide() end\n', '', 'the clicked row tooltip stays over the menu'),
    ('Menu.lua', '    m:Raise()\n', '', 'the menu is not raised'),
    ('Menu.lua', '    C_Timer.After(0, function() if m:IsShown() then layout(m) end end)\n', '', 'menu text measured hidden is never sized again'),
    ('Menu.lua', '    C_Timer.After(0, function() if m:IsShown() then layout(m) end end)', '    C_Timer.After(0, function() layout(m) end)', 'a closed menu is sized again'),
    ('Menu.lua', '    kit.SnapLines(m.edges)\n', '', 'menu edges never re-snapped'),
    ('Menu.lua', '    for i = 1, #items do kit.SnapLines({ m.rows[i].line }) end\n', '', 'divider lines never re-snapped'),
    ('Menu.lua', '    if type(items) ~= "table" or #items == 0 then', '    if type(items) ~= "table" then', 'an empty menu accepted'),
    ('Menu.lua', '        if type(item) ~= "table" then', '        if false then', 'a non-table item accepted'),
    ('Menu.lua', '            if ITEM_FIELDS[key] ~= type(v) then', '            if false then', 'a misspelled item field accepted'),
    ('Menu.lua', '        if item.kind and not KINDS[item.kind] then', '        if false then', 'an unknown kind accepted'),
    ('Menu.lua', '        if item.kind ~= "divider" and not item.text then', '        if false then', 'an item with no text accepted'),
    ('Menu.lua', '        if item.kind ~= "divider" and not item.text then', '        if item.kind == nil and not item.text then', 'a title with no text accepted'),
    ('Menu.lua', 'has a bad or unknown field %s"):format(i, tostring(key)), 2)', 'has a bad or unknown field %s"):format(i, tostring(key)), 1)', 'ShowMenu error points at the library'),
]


def run_tests(root):
    for test in sorted(glob.glob(os.path.join(root, 'tests', 'test_*.lua'))):
        if subprocess.run([LUA, test], capture_output=True).returncode != 0:
            return False
    return True


def main():
    work = tempfile.mkdtemp(prefix='eui-mutate-')
    caught, bad = 0, []
    try:
        lib = os.path.join(work, 'lib')
        if not run_tests(ROOT):
            print('the unmutated tests fail - fix them first')
            return 1
        for rel, old, new, label in MUTANTS:
            if os.path.exists(lib):
                shutil.rmtree(lib)
            shutil.copytree(ROOT, lib, ignore=shutil.ignore_patterns('.git', '__pycache__'))
            path = os.path.join(lib, rel)
            with open(path, encoding='utf-8', newline='') as f:
                text = f.read()
            n = text.count(old)
            if n != 1:
                bad.append('ANCHOR x%d  %s' % (n, label))
                continue
            with open(path, 'w', encoding='utf-8', newline='') as f:
                f.write(text.replace(old, new))
            if run_tests(lib):
                bad.append('SURVIVED  %s' % label)
            else:
                caught += 1
    finally:
        shutil.rmtree(work, ignore_errors=True)
    for line in bad:
        print(line)
    print('%d of %d mutants caught' % (caught, len(MUTANTS)))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
